// Mock products used when Convex is not yet connected (placeholder URL).
// These match the shape ProductCard / ProductGrid / ProductDetails expect.
// Prices are in paise (₹1 = 100 paise).

export const MOCK_PRODUCTS = [
  {
    _id: 'mock_tee_001',
    name: 'Neon Logo Oversized Tee',
    slug: 'neon-logo-oversized-tee',
    description: '240GSM heavyweight cotton. Chest-printed glowing NeechBakra logo in neon green. Boxy fit. Wear it to tournaments, streams, or just flex on everyone.',
    price: 129900,
    compareAtPrice: 159900,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600'],
    category: 'Oversized Tees',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    stock: 100,
    tags: ['tee', 'neon', 'logo', 'bestseller'],
    isFeatured: true,
    isActive: true,
    gradientClass: 'product-gradient-3',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    _id: 'mock_tee_002',
    name: 'Grind Never Stops Tee',
    slug: 'grind-never-stops-tee',
    description: "Bold back-print 'THE GRIND NEVER STOPS' in Orbitron font. 240GSM boxy fit. The everyday uniform for those who run on ambition.",
    price: 119900,
    compareAtPrice: 149900,
    images: ['https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=600'],
    category: 'Oversized Tees',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    stock: 150,
    tags: ['tee', 'grind', 'oversized'],
    isFeatured: true,
    isActive: true,
    gradientClass: 'product-gradient-1',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    _id: 'mock_tee_003',
    name: 'Respawn Graphic Tee',
    slug: 'respawn-graphic-tee',
    description: "Front graphic: pixelated skull with 'RESPAWN IN 3..2..1' text. 220GSM ringspun cotton. The tee that started ten conversations.",
    price: 134900,
    compareAtPrice: 159900,
    images: ['https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600'],
    category: 'Oversized Tees',
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 80,
    tags: ['tee', 'graphic', 'gaming'],
    isFeatured: true,
    isActive: true,
    gradientClass: 'product-gradient-2',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    _id: 'mock_tee_004',
    name: 'Chaos Drop Tee',
    slug: 'chaos-drop-tee',
    description: 'All-over chaos print. Inspired by NeechBakra\'s most chaotic gaming moments. Limited first print run — 200 units only.',
    price: 149900,
    compareAtPrice: null,
    images: ['https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600'],
    category: 'Oversized Tees',
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 200,
    tags: ['tee', 'chaos', 'limited'],
    isFeatured: false,
    isActive: true,
    gradientClass: 'product-gradient-4',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    _id: 'mock_tee_005',
    name: 'NB Acid Wash Tee',
    slug: 'nb-acid-wash-tee',
    description: 'Hand-processed acid wash on 260GSM heavyweight cotton. No two pieces identical. Drop-shoulder fit.',
    price: 169900,
    compareAtPrice: 199900,
    images: ['https://images.unsplash.com/photo-1562157873-818bc0726f68?w=600'],
    category: 'Oversized Tees',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: 60,
    tags: ['tee', 'acid-wash', 'premium'],
    isFeatured: false,
    isActive: true,
    gradientClass: 'product-gradient-3',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    _id: 'mock_tee_006',
    name: 'Ranked Up Tee',
    slug: 'ranked-up-tee',
    description: "For the ones who climbed from Bronze to Legend. Minimal 'RANKED UP' text-print on chest. Ultra-soft 200GSM cotton.",
    price: 99900,
    compareAtPrice: null,
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
    category: 'Oversized Tees',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    stock: 200,
    tags: ['tee', 'ranked', 'minimal'],
    isFeatured: false,
    isActive: true,
    gradientClass: 'product-gradient-5',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
]

export const MOCK_FEATURED = MOCK_PRODUCTS.filter((p) => p.isFeatured)
